/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ValidarRegistroC;
import DAO.ClienteDAO;
import DAO.VehiculoDAO;
import Entidad.Cliente;
import Entidad.Vehiculo;
import static Frontera.RegistroCliente.clientes;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class ActualizacionCliente extends javax.swing.JFrame {

    /**
     * Creates new form ActualizacionCliente
     */
    public ActualizacionCliente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        direccion_L = new javax.swing.JLabel();
        direccionTF = new javax.swing.JTextField();
        telefonoTF = new javax.swing.JTextField();
        telefono_L = new javax.swing.JLabel();
        identificacion_L = new javax.swing.JLabel();
        identificacionTF = new javax.swing.JTextField();
        apellidosTF = new javax.swing.JTextField();
        apellidos_L = new javax.swing.JLabel();
        nombres_L = new javax.swing.JLabel();
        nombresTF = new javax.swing.JTextField();
        actualizar_B = new javax.swing.JButton();
        cancelarB = new javax.swing.JButton();
        actCed_TF = new javax.swing.JTextField();
        cedCambiar_L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        direccion_L.setText("Dirección:");

        telefono_L.setText("Teléfono:");

        identificacion_L.setText("Identificación:");

        apellidos_L.setText("Apellidos:");

        nombres_L.setText("Nombres:");

        actualizar_B.setText("Actualizar");
        actualizar_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_BActionPerformed(evt);
            }
        });

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        cedCambiar_L.setText("Ingrese la cédula del cliente al que quiere actualizar la información");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cancelarB)
                                    .addGap(18, 18, 18)
                                    .addComponent(actualizar_B))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(identificacion_L)
                                        .addComponent(telefono_L)
                                        .addComponent(direccion_L))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(direccionTF, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addComponent(identificacionTF)
                                        .addComponent(telefonoTF))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombres_L)
                                    .addComponent(apellidos_L))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombresTF)
                                    .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(actCed_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(cedCambiar_L)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cedCambiar_L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actCed_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombres_L)
                    .addComponent(nombresTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos_L)
                    .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(identificacion_L)
                    .addComponent(identificacionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono_L)
                    .addComponent(telefonoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion_L)
                    .addComponent(direccionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizar_B)
                    .addComponent(cancelarB))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizar_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_BActionPerformed
            
        Cliente cliente = new Cliente();
        Cliente clienteAct = new Cliente();
        //Vehiculo vehiculo = new Vehiculo();
        //Vehiculo vehiculoAct = new Vehiculo();        
        ClienteDAO daoC = new ClienteDAO();
        VehiculoDAO daoV = new VehiculoDAO();
        List<Vehiculo> vehiculoLista1 =  new ArrayList<Vehiculo>();
        List<Vehiculo> vehiculoLista2 =  new ArrayList<Vehiculo>();
        //String ced = JOptionPane.showInputDialog("Ingrese la cédula del usuario que desea actualizar");         
        String ced = actCed_TF.getText();
        clienteAct = daoC.leer(Long.parseLong(ced));       
        vehiculoLista1 = daoV.leer(Long.parseLong(ced)); //Recibe la lista que envía el método de los resultados en la base de datos
        vehiculoLista2 = vehiculoLista1;
        for(int i=0; i<vehiculoLista1.size(); i++){
            vehiculoLista2.get(i).setCedDueño(Long.parseLong(identificacionTF.getText()));
        }
        //vehiculo = vehiculoAct;
        //vehiculo.setCedDueño(Long.parseLong(identificacionTF.getText()));
        cliente.setNombres(nombresTF.getText());
        cliente.setApellidos(apellidosTF.getText());
        cliente.setCedula(Long.parseLong(identificacionTF.getText()));
        cliente.setTelefono(Long.parseLong(telefonoTF.getText()));
        cliente.setDireccion(direccionTF.getText());        
        ValidarRegistroC verC = new ValidarRegistroC();
        
        //System.out.println(verC.VerificarRegistro(cliente)); <<Banderilla
        if(verC.VerificarActualización(cliente, Long.parseLong(ced)).equals("Usuario registrado con exito")){   
            daoC.actualizar(clienteAct, cliente);
            for(int i=0; i< vehiculoLista1.size(); i++){
                daoV.actualizar(vehiculoLista1.get(i), vehiculoLista2.get(i));
            }            
            //clientes.add(cliente);
            JOptionPane.showMessageDialog(null, "Usuario actualizado con exito 1");
            JOptionPane.showMessageDialog(null, "La info. de los vehículos del cliente también fue actualizada");
            Menu obj = new Menu();
            obj.setVisible(true);
            this.dispose();
        }
        else if(Long.parseLong(identificacionTF.getText()) == Long.parseLong(ced) && verC.VerificarRegistro(cliente).equals("La cedula ya esta registrada")){
            daoC.actualizar(clienteAct, cliente);
            //daoV.actualizar(vehiculoAct, vehiculo);
            //clientes.add(cliente);
            JOptionPane.showMessageDialog(null, "Usuario actualizado con exito 2");
            JOptionPane.showMessageDialog(null, "Usted no hizo cambios en la cédula, los vehículos mantienen su información");
            Menu obj = new Menu();
            obj.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, verC.VerificarActualización(cliente, Long.parseLong(ced)));
        }

    }//GEN-LAST:event_actualizar_BActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizacionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizacionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actCed_TF;
    private javax.swing.JButton actualizar_B;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JLabel apellidos_L;
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel cedCambiar_L;
    private javax.swing.JTextField direccionTF;
    private javax.swing.JLabel direccion_L;
    private javax.swing.JTextField identificacionTF;
    private javax.swing.JLabel identificacion_L;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombresTF;
    private javax.swing.JLabel nombres_L;
    private javax.swing.JTextField telefonoTF;
    private javax.swing.JLabel telefono_L;
    // End of variables declaration//GEN-END:variables
}
