/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.CalculoPrecioServicio;
import Control.ValidarRegistroF;
import DAO.ClienteDAO;
import DAO.EmpleadoDAO;
import DAO.FacturaDAO;
import DAO.ProductoDAO;
import DAO.ServicioDAO;
import DAO.VehiculoDAO;
import Entidad.Cliente;
import Entidad.Empleado;
import Entidad.Factura;
import Entidad.Producto;
import Entidad.Servicio;
import Entidad.Vehiculo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
/**
 *
 * @author Marcos
 */
public class Facturacion extends javax.swing.JFrame {

    DefaultComboBoxModel modeloClientes, modeloVehiculos, modeloUsoProd, modeloServ;
    Empleado emp = new Empleado();
    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
        cargarCliente(); 
        cargarProducto();
        panelSecundario.setVisible(false);
        AutoCompleteDecorator.decorate(clientesCBX);
        setLocationRelativeTo(null);
    }
    
    public void cargarCliente(){ //Método que permite leer la base de datos de Cliente y cargar en el JComboBox las cédulas existentes
        List<Cliente> cliente =  new ArrayList<Cliente>();
        ClienteDAO daoC = new ClienteDAO();
        cliente = daoC.leer();
        String[] arregloClientes = new String[cliente.size()];
        for(int i = 0; i<cliente.size(); i++){
            arregloClientes[i] = Long.toString(cliente.get(i).getCedula());            
        }
        modeloClientes = new DefaultComboBoxModel(arregloClientes);
        clientesCBX.setModel(modeloClientes);
    }
    public final void cargarVehiculo(){ //Método que permite leer la base de datos de vehículos y cargar en el JComboBox los vehículos existentes según el cliente seleccionado
        String cedulaD = clientesCBX.getSelectedItem().toString();
        List<Vehiculo> vehiculo =  new ArrayList<Vehiculo>();
        VehiculoDAO daoV = new VehiculoDAO();
        cedulaD = cedulaD.replaceAll(" ", ""); //para evitar errores de espacios
        if(cedulaD != null && !cedulaD.equals("")){//para evitar errores de exepciones de formato
            vehiculo = daoV.leer(Long.parseLong(cedulaD));
            String[] arregloVehiculos = new String[vehiculo.size() + 1];
            arregloVehiculos[0] = "Sin servicio";
            for(int i = 1; i<=vehiculo.size(); i++){
                arregloVehiculos[i] = vehiculo.get(i-1).getMatricula();            
            }
            modeloVehiculos = new DefaultComboBoxModel(arregloVehiculos);
            vehiculosCBX.setModel(modeloVehiculos);
        }        
    }
    public void cargarProducto(){ //Método que permite leer la base de datos de productos y cargar en el JComboBox los tipos de productos existentes
        List<Producto> producto =  new ArrayList<Producto>();
        ProductoDAO daoP = new ProductoDAO();
        producto = daoP.leer();
        String[] arregloProductos = new String[producto.size() + 1];
        arregloProductos[0] = "Sin producto";
        for(int i = 1; i<=producto.size(); i++){
            arregloProductos[i] = producto.get(i-1).getNombre();            
        }
        modeloUsoProd = new DefaultComboBoxModel(arregloProductos);
        productosCBX.setModel(modeloUsoProd);
    }
    public void cargarServicio(){ //Método que permite leer la base de datos de servicios y cargar en el JComboBox los tipos de servicios existentes
        String confCBX = vehiculosCBX.getSelectedItem().toString();
        if(confCBX.equals("Sin servicio")){
            String[] arregloServicios = new String[1];
            arregloServicios[0] = "Sin servicio";
            modeloServ = new DefaultComboBoxModel(arregloServicios);
        }
        else{
            List<Servicio> servicio =  new ArrayList<Servicio>();
            ServicioDAO daoS = new ServicioDAO();
            servicio = daoS.leer();
            String[] arregloServicios = new String[servicio.size()];          
            for(int i = 0; i<servicio.size(); i++){
                arregloServicios[i] = servicio.get(i).getNombreservicio(); 
                modeloServ = new DefaultComboBoxModel(arregloServicios);
            }            
        }           
        serviciosCBX.setModel(modeloServ);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        mensaje1L = new javax.swing.JLabel();
        clientesCBX = new javax.swing.JComboBox<>();
        vehiculosCBX = new javax.swing.JComboBox<>();
        mensaje2L = new javax.swing.JLabel();
        mensaje3L = new javax.swing.JLabel();
        productosCBX = new javax.swing.JComboBox<>();
        mensaje4L = new javax.swing.JLabel();
        serviciosCBX = new javax.swing.JComboBox<>();
        passwordPF = new javax.swing.JPasswordField();
        mensaje5L = new javax.swing.JLabel();
        validarB = new javax.swing.JButton();
        AvisoGdL = new javax.swing.JLabel();
        volverB = new javax.swing.JButton();
        panelSecundario = new javax.swing.JPanel();
        precioL = new javax.swing.JLabel();
        facturarB = new javax.swing.JButton();
        avisoPrecioL = new javax.swing.JLabel();
        cancelarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensaje1L.setText("1. Seleccione la cédula del cliente");

        clientesCBX.setEditable(true);
        clientesCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        clientesCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesCBXActionPerformed(evt);
            }
        });

        vehiculosCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin servicio" }));
        vehiculosCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculosCBXActionPerformed(evt);
            }
        });

        mensaje2L.setText("2. Matrícula si se tomó un servicio");

        mensaje3L.setText("3. Elija el producto a facturar");

        productosCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productosCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosCBXActionPerformed(evt);
            }
        });

        mensaje4L.setText("4. Servicio");

        serviciosCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin servicio" }));
        serviciosCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviciosCBXActionPerformed(evt);
            }
        });

        passwordPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPFActionPerformed(evt);
            }
        });

        mensaje5L.setText("<html>5.Contraseña empreado.<br/>Valide la transacción");

        validarB.setText("Validar");
        validarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarBActionPerformed(evt);
            }
        });

        AvisoGdL.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        AvisoGdL.setText("Facturación");

        volverB.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        volverB.setText("volver");
        volverB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje2L)
                    .addComponent(vehiculosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaje4L)
                    .addComponent(serviciosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje3L)
                    .addComponent(productosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaje5L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(validarB))))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(clientesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mensaje1L)))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(volverB)
                .addGap(66, 66, 66)
                .addComponent(AvisoGdL, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AvisoGdL))
                    .addComponent(volverB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensaje1L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clientesCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mensaje2L)
                    .addComponent(mensaje3L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiculosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mensaje5L, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaje4L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviciosCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validarB)
                .addGap(158, 158, 158))
        );

        precioL.setText("Aquí va el precio");

        facturarB.setText("Facturar");
        facturarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturarBActionPerformed(evt);
            }
        });

        avisoPrecioL.setText("El valor a facturar es:");

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSecundarioLayout = new javax.swing.GroupLayout(panelSecundario);
        panelSecundario.setLayout(panelSecundarioLayout);
        panelSecundarioLayout.setHorizontalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSecundarioLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelarB)
                    .addComponent(avisoPrecioL))
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(facturarB))
                    .addGroup(panelSecundarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(precioL, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        panelSecundarioLayout.setVerticalGroup(
            panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSecundarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avisoPrecioL)
                    .addComponent(precioL, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(panelSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facturarB)
                    .addComponent(cancelarB))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 279, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesCBXActionPerformed
        String[] auxSS = {"Sin servicio"};
        modeloServ = new DefaultComboBoxModel(auxSS);
        serviciosCBX.setModel(modeloServ);
        cargarVehiculo();
        panelSecundario.setVisible(false);
    }//GEN-LAST:event_clientesCBXActionPerformed

    private void validarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarBActionPerformed
        EmpleadoDAO daoE = new EmpleadoDAO();
        emp = daoE.leer(passwordPF.getText());     
        if(emp != null){
            float precioServicio = 0, precioProducto = 0, precioTotal = 0;       
            if(serviciosCBX.getSelectedItem().toString().equals("Sin servicio")){
              precioServicio = 0;  
            }else{
                VehiculoDAO daoV = new VehiculoDAO();
                ServicioDAO daoS = new ServicioDAO();
                Vehiculo vehAux = new Vehiculo();
                Servicio serAux = new Servicio(); 
                CalculoPrecioServicio calculoServ = new CalculoPrecioServicio();

                vehAux = daoV.leer(vehiculosCBX.getSelectedItem().toString()); //objeto que guarda el tipo de vehiculo
                serAux = daoS.leer(serviciosCBX.getSelectedItem().toString());//objeto que guarda el tipo de servicio
                precioServicio = calculoServ.calcularPrecioServicio(serAux, vehAux);
            }
            if(productosCBX.getSelectedItem().toString().equals("Sin producto")){
                precioProducto = 0;
            }
            else{
                ProductoDAO daoP = new ProductoDAO();
                precioProducto = daoP.leer(productosCBX.getSelectedItem().toString()).getPrecioVenta();
            }
            precioTotal = precioServicio + precioProducto;        
            String aux = String.valueOf(precioTotal);//Calcular el precio total con las clases control de calcular y asignar a la variable
            precioL.setText(aux);    
            panelSecundario.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "La contraseña no es correcta");    

        
        
    }//GEN-LAST:event_validarBActionPerformed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarBActionPerformed

    private void volverBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBActionPerformed
        Menu obj = new Menu();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBActionPerformed

    private void facturarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturarBActionPerformed
        Factura factura = new Factura();
        FacturaDAO daoF = new FacturaDAO();
        factura.setPrecio(Float.parseFloat(precioL.getText()));
        factura.setCedulacliente(Long.parseLong(clientesCBX.getSelectedItem().toString()));
        factura.setAutoCliente(vehiculosCBX.getSelectedItem().toString());
        factura.setServicioTomado(serviciosCBX.getSelectedItem().toString());
        factura.setProductoComprado(productosCBX.getSelectedItem().toString());
        factura.setIdempleado(emp.getId());
        //Llenar el objeto factura con la información que se toma de la interfaz
        ValidarRegistroF verF = new ValidarRegistroF();
        if(verF.validarRegistro(factura).equals("Exito en registro de factura")){
            daoF.crear(factura);
            JOptionPane.showMessageDialog(null, "Transacción realizada exitosamente");
            Menu obj = new Menu();
            obj.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, verF.validarRegistro(factura));
            panelSecundario.setVisible(false);
        }
        
    }//GEN-LAST:event_facturarBActionPerformed

    private void vehiculosCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculosCBXActionPerformed
        cargarServicio();
        panelSecundario.setVisible(false);
    }//GEN-LAST:event_vehiculosCBXActionPerformed

    private void serviciosCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviciosCBXActionPerformed
        panelSecundario.setVisible(false);
    }//GEN-LAST:event_serviciosCBXActionPerformed

    private void productosCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosCBXActionPerformed
        panelSecundario.setVisible(false);
    }//GEN-LAST:event_productosCBXActionPerformed

    private void passwordPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AvisoGdL;
    private javax.swing.JLabel avisoPrecioL;
    private javax.swing.JButton cancelarB;
    private javax.swing.JComboBox<String> clientesCBX;
    private javax.swing.JButton facturarB;
    private javax.swing.JLabel mensaje1L;
    private javax.swing.JLabel mensaje2L;
    private javax.swing.JLabel mensaje3L;
    private javax.swing.JLabel mensaje4L;
    private javax.swing.JLabel mensaje5L;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel precioL;
    private javax.swing.JComboBox<String> productosCBX;
    private javax.swing.JComboBox<String> serviciosCBX;
    private javax.swing.JButton validarB;
    private javax.swing.JComboBox<String> vehiculosCBX;
    private javax.swing.JButton volverB;
    // End of variables declaration//GEN-END:variables
}
